### ISSUE TITLE
notmuch install instructions outdated?

### ISSUE THREAD

**Issue by DivineDominion** [vedang/emacs-up#2]
Found this line: 
https://github.com/vedang/emacs-up/blob/0ceb1fab3158ef2ca615f3c1554221f94c173601/init.el#L107

    $ brew install notmuch --with-emacs

But `brew info notmuch` shows that there's no `--with-emacs` option (anymore?). I think you can safely remove this comment. 

I also just installed notmuch yesterday and the emacs package works fine with it out of the box 👍

**Comment by vedang** [comment]
Thanks, I've made the change in e42c31a and fixed it :+1:
